### ISSUE TITLE
[Feature] Vise "fyllingsgrad" basert på historiske data

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/leveranser#71]
## Origin

_Links to received feedback, user research or other findings._

## Motivation

_A short description of what user needs or business goals this feature will solve._

> Som en reisende med særskiltebehov til plass, enten det er tetthet for Covid-19, rullestol, barnevogn eller ønske om å ta med sykkel, ønsker jeg bedre grunnlag til å vurdere hvilken reisemetode og buss jeg burde ta.﻿

> Målet er å fordele de reisende på flere avganger for å redusere trengsel både mht til smittevern (kort sikt) og generell kapasitetsutnyttelse på sikt. Kan gi kunden veiledning til å velge en annen avgang eller en annen reisevei om det er bedre for de.

## Hypotheses and assumptions

_A list of hypotheses and assumptions we have made about the user or the proposed solution._

## Proposed solution

_A coarse description of a proposed solution, that may include wireframes and graphic design._

## Tasks

- [ ] Initial design
- [ ] Setup SQL Standard Database
- [ ] Implement first version in App.
- [ ] Validate value/confirm hypotheses

## Acceptance Criteria

_List of relevant acceptance criteria as a part of a QA flow_

- [ ] Renders colors as expected in dark and light mode.
- [ ] Is translatable to English and Norwegian.
- [ ] Does not drain battery
- [ ] Works in up to 200% font size
- [ ] Is operable and perceivable using screen reader
