### ISSUE TITLE
Avganger v2: Ferdigstille fase 2

### ISSUE THREAD

**Issue by rosvik** [AtB-AS/leveranser#81]
- [x] AtB-AS/mittatb-app#2012
- [x] AtB-AS/mittatb-app#2014
- [ ] AtB-AS/mittatb-app#2013
- [x] AtB-AS/mittatb-app#2015
- [x] https://github.com/AtB-AS/mittatb-app/issues/2076
- [x] AtB-AS/mittatb-app#2046
- [x] AtB-AS/mittatb-app#2090

**Comment by tormoseng** [comment]
UU-observasjoner til fase 2:
- Plattformvelgerne kan gi litt mer info som ex "Aktiver for å vise avganger fra plattform Kongens gate K1"
- Velg annen dag så gir aktuell dag klokkeslett som "Valgt dato 22.januar 0"
- Forrige og Neste dag gir kun beskjed om "knapp"
- Burde opplesning av en linje også lese opp den valgte dagen og ikke kun klokkeslett når en dag i fremtiden er valgt?
- Tidsvelger sier bare "0" når klokka er "00:00"
- Avgangsmeny-punktet velges/fokuseres etter å ha bekreftet en dato/tid i datovelger
- Hvis man endrer tid i dag så leses valgt dato opp som ex "21.januar 13:19" og ikke "i dag 13:19"
- Fokus på en avgang gir ingen info om at man kan åpne for å vise detaljer
- Åpning av en avgang i detaljvisningen leser opp ex "forventet tid Prinsens gate P1"

**Comment by hildeor** [comment]
Lukker da denne er duplikat av https://github.com/AtB-AS/mittatb-app/issues/1394

**Comment by gorandalum** [comment]
Gjenåpner denne da dette er produktinitiativ-saken som trackes på Leveranse-boardet.
